project:
  type: book
  output-dir: _book

format:
  html:
    theme: cosmo
    toc: true
    mathjax: true  # needed for HTML output
    toc-depth: 3
    margin-header: " "
    number-sections: true
    toc-title: "On this page"
    sidebar:
      logo: "img/FairfielduShield.o.png"
      logo-alt: "My Book Logo"
      style: "docked"
 
#filters:
#    - title-color.lua

metadata-files:
  - _assigned.yaml
  - yml_toc.yml


