#  Quantum Mechanics of the Electron
## Quantum Mechanics of the Electron (4:01) { .unnumbered}
<iframe style="width: 100%; aspect-ratio: 16/9" src="https://www.youtube.com/embed/t8mMN2X5_Vw" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>


::: {.callout-note}
You will find more excellent videos at this content creater's [YouTube Channel](https://www.youtube.com/@ProfessorDaveExplains)
:::
 

    
## Quantum Mechanics of the Electron  Video Transcript { .unnumbered}


Hey guys, it's Professor Dave. Let's talk about quantum mechanics. We have seen how the first steps into quantum theory gave us the idea that all energy is not continuous but quantized, and that light obeys wave-particle duality. The next idea came courtesy of Louis de Broglie—pardon my poor French pronunciation. He reasoned that if waves can behave like particles, then particles must also behave like waves. In his de Broglie relation, he showed that the wavelength of a particle is inversely proportional to its mass. Therefore, we must now understand that all matter has a wavelength, from subatomic particles all the way up to your body and even a star. 

A macroscopic object like a baseball will have a wavelength that is trillions of times smaller than the nucleus of an atom, so we don't need to think of baseballs as waves. Newtonian mechanics work just fine to describe the motion of objects we can see. However, an electron has a wavelength that is very significant compared to its actual size, so we can no longer think of electrons as particles; we must think of them as both a particle and a wave. Wave-particle duality just got extended from light to matter.

Erwin Schrödinger wanted a way to describe the wave mechanics of the electron, so he developed quantum mechanics to do just that. As a result, we can no longer think of an atom as electrons revolving around a nucleus the way planets revolve around a star. We have to think of an electron as a cloud of probability density that represents regions where the electron can be found. 

Werner Heisenberg soon showed that as a result of quantum mechanics, there are fundamental limitations to what we can know about a particle like an electron, so he formulated his uncertainty principle. The main ramification for chemistry is that the more we know about the location of an electron, the less we know about what it's doing or its momentum. Conversely, the more we know about what it's doing, the less we know about its location. This has nothing to do with the limitations of our measuring instruments; it is an inherent quality of the electron. 

If we could know both its location and momentum with complete certainty, then we could describe it as merely a particle, but it is not a particle; it is both a particle and a wave. This seems to defy common sense, so how can it be true? We have to get used to the fact that common sense doesn't make for good science. Nature is governed by mathematical equations, not by human perceptions of how things should be. 

So when the math says that electrons are both particles and waves, or that space is curved around massive objects, or that time flows at different rates for different observers, we have to accept that this is a deeper tier of reality than what we can immediately perceive and comprehend. It seems like common sense that the sun goes around the earth, which is why we believed it for so long, but mathematical calculations made by several astronomers forced us to accept that it is the earth that goes around the sun, because their model predicted the locations of celestial objects with more precision. 

We can't look back at the solar system from afar, but we don't have to. The math is the evidence. It is our understanding of mathematics that allows us to transcend our five senses and discover the true nature of the universe, from the tiniest particles to the galaxies and beyond. Thanks for watching, guys! Subscribe to my channel for more tutorials, and as always, feel free to email me.


{{< include ../_text1.qmd >}}

{{< include ../_text2.qmd >}}

{{< include ../_footer.qmd >}}
